<?php

/**
 * @file
 * Contains guestbook_theme.
 */

/**
 * Implements hook_theme().
 */
function guestbook_theme($existing, $type, $theme, $path) {
  return [
    "guestbook-theme" => [
      "variables" => [
        'form' => NULL,
        'revues' => NULL,
      ],
    ],
    'guestbook-table-block' => [
      'variables' => [
        'name' => NULL,
        'email' => NULL,
        'phone' => NULL,
        'textmessage' => NULL,
        'avatar' => NULL,
        'image' => NULL,
        'date' => NULL,
        'id' => NULL,
      ],
    ],
  ];
}
